name: KWPlugin
main: org.kwstudios.play.bungeelobby.loader.PluginLoader
version: 1.0.1

commands:
  setlobby:
    description: Sets the Server Lobby to the current position!
    permission: kwplugin.lobbymanager.setlobby
    permission-message: You may not set the Lobby!
  lobby:
    description: Teleports the player to the lobby!
    aliases: ['l', 'spawn']
    permission: kwplugin.lobbymanager.lobby
    permission-message: You may not teleport yourself to the lobby!
  kwlist:
    description: Shows all the players who ever played on this server!
    permission: kwplugin.server.list
    permission-message: You may not use that command!
  kwreload:
    description: Reloads the config.yml from list!
    permission: kwplugin.server.list
    permission-message: You may not use that command!
  kwinit:
    description: Inits the API for all the Players!
    permission: kwplugin.api.init
    permission-message: You may not use that command!
