name: KWPlugin
main: org.kwstudios.play.loader.PluginLoader
version: 0.2.1

commands:
  setlobby:
    description: Sets the Server Lobby to the current position!
    permission: kwplugin.lobbymanager.setlobby
    permission-message: You may not set the Lobby!
  lobby:
    description: Teleports the player to the lobby!
    aliases: ['l', 'spawn']
    permission: kwplugin.lobbymanager.lobby
    permission-message: You may not teleport yourself to the lobby!
  kwlist:
    description: Shows all the players who ever played on this server!
    permission: kwplugin.server.list
    permission-message: You may not use that command!
  kwreload:
    description: Reloads the config.yml from list!
    permission: kwplugin.server.list
    permission-message: You may not use that command!