name: KWBungeeLobby
main: org.kwstudios.play.kwbungeelobby.loader.PluginLoader
version: 1.0.2

commands:
  kwlobby:
    description: Main command.
    permission: kwstudios.lobby
    permission-message: There are some sort of commands which are not intended to be used by certain players...
  kwlobby cc:
    description: Adds a RageMode map with the given name and the maximum player count.
    permission: kwstudios.lobby.createcompass
    permission-message: There are some sort of commands which are not intended to be used by certain players...
  kwlobby reload:
    description: Reloads the plugin.
    permission: kwstudios.lobby.reload
    permission-message: There are some sort of commands which are not intended to be used by certain players...
    
permissions:
  kwstudios.lobby:
    description: Gives access to the main command.
    default: op
  kwstudios.lobby.*:
    description: Gives access to all lobby commands.
    default: op
    children:
      kwstudios.lobby.createcompass: true
      kwstudios.lobby.reload: true
      kwstudios.lobby.interact: true
